import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
// import enMessages from '/messages/en.json';
// import arMessages from '/messages/ar.json';
// import Navbar from "@/components/Navbar";
// import { NextIntlClientProvider } from "next-intl";
import React from "react";
import { notFound } from "next/navigation";
import { getLocale } from 'next-intl/server'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500"],
  style: ["normal", "italic"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// export default async function RootLayout({ children, params }) {
export default async function RootLayout({ children}) {


  return (
    // <html lang={locale}>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${roboto.variable} `}
      >
        {/* <NextIntlClientProvider locale={locale} messages={messages}>  */}
          {children}
        {/* </NextIntlClientProvider> */}
      </body>
    </html>
  );
}
